### ISSUE TITLE
G+ icon overflows width

### ISSUE THREAD

**Issue by bjornbjorn** [brianegan/font_awesome_flutter#1]
Hi :) I'm not sure if this is the right place to report this issue (apologies if not, just close it if so)  -- but I'm having an issue with a specific icon - the G+ one, which seems to be wider than what it is reporting ..

So, this Flutter code:

```new Row(
                              children: [
                                new Icon(FontAwesomeIcons.googlePlus),
                                new Text('Logg inn med Google')
                              ]
                          ),
```

.. will cause the Icon to overlap the text on the right.

See example with the G+ icon in the second FlatButton here: http://i.imgur.com/TXAhJr2.png
Other icons, ie. the Facebook f and Google Plus squared work fine: http://i.imgur.com/HgDmmIj.png

**Comment by brianegan** [comment]
Thanks for the report! Sorry, not sure why Github didn't ping me on this one :(

I'll take a look and see what's up. I wonder if the Font Awesome font might not be quite reporting the right width for this icon.

**Comment by brianegan** [comment]
Ok, took a look at this and was able to reproduce. I would assume there would be differences in size (it's not a monospace font, after all), but It looks like the glyph simply takes up more room than it reports :(

The way the Font Awesome package gets around this is to provide CSS classes with a fixed width & center the icon within that container. I'd recommend going the same route. Not ideal, but I don't think I can do anything to fix it.

**Comment by erperejildo** [comment]
I just tried latest version and it still having this issue:
![Screenshot_1577623175](https://user-images.githubusercontent.com/5629919/71557038-bae40280-2a40-11ea-8da4-86a5b4ccab2a.png)
