### ISSUE TITLE
Missing the cookie and cookie-bite icons

### ISSUE THREAD

**Issue by tom-s07** [brianegan/font_awesome_flutter#15]
For some reason it seems some of the free FA icons are not included in the package. 
How can I add missing icons by hand?

**Comment by theblackcat102** [comment]
Facebook icons seems to be missing as well

**Comment by brianegan** [comment]
Thanks! Looks like I need to re-generate the icon pack since they're released 5.1.0.

**Comment by brianegan** [comment]
Just pushed up a new version: 7.1.0, which includes the Cookie and Cookie-bite icons
