### ISSUE TITLE
Integrating font awesome pro

### ISSUE THREAD

**Issue by techyrajeev** [brianegan/font_awesome_flutter#17]
How can I add font-awesome pro features with this plugin?
Is there any way to integrate font awesome pro licence key with `font-awesome-flutter` so that all pro fonts are also available for use?

**Comment by brianegan** [comment]
Hey there -- sorry, not sure how I missed your issue :/

This library is open source and can only support the free icons. If you'd like to create a version with the pro icons, please check out the `tool/update.sh` file. You could definitely adapt it to read not only the free but also the commercial icons.

**Comment by Samaritan1011001** [comment]
@brianegan @techyrajeev are there any steps or anything I can use to get the pro working with this package since I don't have much knowledge about this. Any help is appreciated. Thank you.

**Comment by herkulano** [comment]
@brianegan merging https://github.com/brianegan/font_awesome_flutter/pull/37 would be super helpful.

**Comment by geek-sajjad** [comment]
how can i create i new package just like this package to using pro icons in my own project ?

**Comment by matthewp672261** [comment]
I realize this may be irrelevant for the sake of this package, but after struggling to get the Pro icons integrated, I stumbled across http://fluttericon.com. It lets you draw the Pro SVGs into it, choose the ones you want and exports the font and Dart class file you need to get it working. AMAZING!

**Comment by coditori** [comment]
@[matthewp672261](https://github.com/matthewp672261) It's not working for duotone type of icons
