### ISSUE TITLE
Version 0.7.1 is incompatible with Dart SDK

### ISSUE THREAD

**Issue by SNNikitin** [brianegan/font_awesome_flutter#18]
After `flutter upgrade` I got error with following message as response to `flutter packages get`:

```
The current Dart SDK version is 2.1.0-dev.0.0.flutter-be6309690f.
Because app depends on font_awesome_flutter >=4.7.1 which requires SDK version <2.0.0, 
version solving failed.
```

Building failed.

**Comment by brianegan** [comment]
Hey there -- I just published the latest version: `8.0.0`, which explicitly supports Dart 2. Please upgrade to the latest version and let me know if ya run into any problems!
