### ISSUE TITLE
Fontawesome Spinner icon is not spinning

### ISSUE THREAD

**Issue by techyrajeev** [brianegan/font_awesome_flutter#20]
I have used spinner icon as below but some how it is not spinning. It is just stuck with load icon.

           Align(
                   alignment: Alignment.centerRight,
                   child: IconButton(
                     icon: Icon(
                       FontAwesomeIcons.spinner,
                       color: Colors.white,
                       size: [18.0,]
                     ),
                     onPressed: () {}
                   ),
                 ),
```

```
<img width="345" alt="screen shot 2018-09-03 at 2 37 09 pm" src="https://user-images.githubusercontent.com/4118032/44977945-1d310e00-af87-11e8-9699-9bc229006a31.png">

**Comment by brianegan** [comment]
Hey there -- good catch! Hrm, perhaps I should add support for this out of the box. At this moment, this package only provides the Icons, but those Icons do not spin or animate by themselves.

To make an Icon Spin, you'd need to use Flutter's animation capabilities, specifically an `AnimationController` and the `RotationTransition` classes.

To make this work, you can use the following Widget, which works with any Icon:

### Usage

```dart
Spinner(
  icon: FontAwesomeIcons.spinner,
)
```

### Spinner Widget

```dart
class Spinner extends StatefulWidget {
  final IconData icon;
  final Duration duration;

  const Spinner({
    Key key,
    @required this.icon,
    this.duration = const Duration(milliseconds: 1800),
  }) : super(key: key);

  @override
  _SpinnerState createState() => _SpinnerState();
}

class _SpinnerState extends State<Spinner> with SingleTickerProviderStateMixin {
  AnimationController _controller;
  Widget _child;

  @override
  void initState() {
    _controller = AnimationController(
      vsync: this,
      duration: Duration(milliseconds: 2000),
    )..repeat();
    _child = Icon(widget.icon);

    super.initState();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return RotationTransition(
      turns: _controller,
      child: _child,
    );
  }
}
```

**Comment by techyrajeev** [comment]
I have used [https://docs.flutter.io/flutter/material/CircularProgressIndicator/CircularProgressIndicator.html](CircularProgressIndicator) for now.

**Comment by techyrajeev** [comment]
But would definitely like to have it's support in built :+1:

**Comment by ishwarchandratiwari** [comment]
i used a material design circular progress indicator which shows progress along a circle

import 'package:font_awesome_flutter/font_awesome_flutter.dart';

class MyWidget extends StatelessWidget {
  Widget build(BuildContext context) {
    return new CircularProgressIndicator();
  }
}
