### ISSUE TITLE
Rectangular icons are centered incorrectly

### ISSUE THREAD

**Issue by bartektartanus** [brianegan/font_awesome_flutter#23]
![image](https://user-images.githubusercontent.com/3193882/48096084-99113600-e216-11e8-8c0c-8ce070fefc1b.png)

Code sample:
```dart
new CircleAvatar(child: new Icon(FontAwesomeIcons.users,size: 70.0, color: Colors.white,),
        backgroundColor: Colors.orange, radius: 70.0,);
```

Next example (this time from your documentation). `IconButton` repeated three times in `Row`. As you can see one icon overlaps another.
![image](https://user-images.githubusercontent.com/3193882/48096862-a92a1500-e218-11e8-9bb4-8ba8798d1a6f.png)

```dart
var button = new IconButton(
    iconSize: 100.0,
    icon: new Center(child:new Icon(FontAwesomeIcons.gamepad,)),
    alignment: Alignment.bottomRight,
    onPressed: () { print("Pressed"); }
);
Row(mainAxisAlignment: MainAxisAlignment.center,children: <Widget>[button, button, button],)
```

**Comment by brianegan** [comment]
Thanks all -- I've taken a look at this issue and determined that there might be a problem with the Flutter framework, so I've opened this issue: https://github.com/flutter/flutter/issues/24054.

All I do with this package is package the font + make some nice methods to access the icons in the font. Flutter handles all of the rendering / positioning here.

Please follow that thread for updates!

**Comment by lore-co** [comment]
Sadly it looks like the problem is still present

**Comment by michaelspiss** [comment]
Hi, please use `FaIcon` instead of material's `Icon` class
