### ISSUE TITLE
icon "fa-user" from Solid font-kit is inaccessible

### ISSUE THREAD

**Issue by odhs** [brianegan/font_awesome_flutter#26]
Icon "fa-user" from Solid font-kit is inaccessible, instead we have the fa-user from regular font-kit.
Would be great if we could select which font style we want the icon. Something like FontAwesomeRegular.user and FontAwesomeSolid.user 

Othe think, the icon "fa-mug-hot" is not in files yet. 

Thank you in advance for attention!

**Comment by brianegan** [comment]
Hey there -- for all of the solid fonts, we've prefixed them with `solid`. So you should be able to use `FontAwesomeIcons.solidUser`. 

And thanks! Sounds like there might be a new version. I'll do an update and see :)

**Comment by odhs** [comment]
Thank you! This work for me!

**Comment by prashant3285** [comment]
> Hey there -- for all of the solid fonts, we've prefixed them with `solid`. So you should be able to use `FontAwesomeIcons.solidUser`. Does that work for ya?
> 
> And thanks! Sounds like there might be a new version. I'll do an update and see :)

Adding this to documentation would be good
