### ISSUE TITLE
Signature icon upside-down?

### ISSUE THREAD

**Issue by stevenspiel** [brianegan/font_awesome_flutter#30]
Font Awesome [lists their signature icon as looking like this](https://fontawesome.com/icons/signature?style=solid):

<img width="121" alt="screen shot 2019-02-04 at 5 17 51 pm" src="https://user-images.githubusercontent.com/1630091/52241095-d9796200-28a0-11e9-99c0-e149c907b8a8.png">

But when I use it in my app, I'm getting something different:

`Icon(FontAwesomeIcons.signature)`

<img width="66" alt="screen shot 2019-02-04 at 5 18 57 pm" src="https://user-images.githubusercontent.com/1630091/52241175-02015c00-28a1-11e9-8d1e-76b53dc6f0fb.png">

I'm using the latest version (8.4.0) and when I switch the icon out for any other, it looks normal.

**Comment by brianegan** [comment]
Hrm, that is super odd -- "Works on my machine" kinda thing. Do you know if there's anything else that might be affecting the Widget to flip the icon? Is that screenshot from iOS or Android?

As a test, could you also try running the demo app found in the `example` folder on your machine? The following screenshot comes from that example, and appears to be correct. 

![screenshot_1549356738](https://user-images.githubusercontent.com/126604/52262105-c364b380-292b-11e9-904d-3e4efcf50852.png)

**Comment by stevenspiel** [comment]
When I opened the app this morning, it was working. I guess a computer reboot did it. Thanks!
