### ISSUE TITLE
chevronUp icons are centered incorrectly

### ISSUE THREAD

**Issue by mirkancal** [brianegan/font_awesome_flutter#33]
Someone asked a question about it on stackoverflow and I've done some tests with Show Debug Paint.

This could be related to these icons.

[Centering child widget icon](https://stackoverflow.com/questions/54932743/flutter-centering-child-widget-icon/54933040#54933040)

**Comment by mirkancal** [comment]
https://github.com/flutter/flutter/issues/24054

Applied that workaround, it's not pixel perfect with chevronCircleUp icon and size 100.0 , but it's good enough

**Comment by brianegan** [comment]
Thanks for the report! Yep, that's the correct fix. 

I took a quick measurement with that fix and it appeared to be just slightly off center. After comparing it to the web version, it looked like that one was also off just a tiny amount as well.
