### ISSUE TITLE
Icon centering

### ISSUE THREAD

**Issue by CosmicPangolin** [brianegan/font_awesome_flutter#36]
Hey Brian,

I'm loving these icons, but some of them graphically seem shifted relative to their widget constraints - see how the 'users' icon is shifted to the right on this TabBar:

![image](https://user-images.githubusercontent.com/40650466/54798363-abb06880-4c15-11e9-9e80-5a326867f816.png)

Not an issue that rears its head often, but some widget orientations (like the above icon cross-axis centered in a column) look pretty off without adjustment. Is there an easy fix?

**Comment by brianegan** [comment]
Yah, this is fixable! Please see this comment / issue for a fix: https://github.com/flutter/flutter/issues/24054#issuecomment-439167235

**Comment by CosmicPangolin** [comment]
Oh word, thanks. The hax will do for now.
