### ISSUE TITLE
Installation Doesn't Work with Android SDK v#>2

### ISSUE THREAD

**Issue by patientplatypus** [brianegan/font_awesome_flutter#41]
```
Peters-MacBook-Pro:flutter patientplatypus$ flutter packages upgrade
The current Dart SDK version is 2.3.0-dev.0.5.flutter-a1668566e5.       
                                                                        
Because yaddayaddayadda depends on font_awesome_flutter >=4.7.1 <8.0.0 which requires SDK version <2.0.0, version solving failed.
Running "flutter packages upgrade" in flutter...                        
pub upgrade failed (1)
```

**Comment by mikeon** [comment]
> ```
> Peters-MacBook-Pro:flutter patientplatypus$ flutter packages upgrade
> The current Dart SDK version is 2.3.0-dev.0.5.flutter-a1668566e5.       
>                                                                         
> Because yaddayaddayadda depends on font_awesome_flutter >=4.7.1 <8.0.0 which requires SDK version <2.0.0, version solving failed.
> Running "flutter packages upgrade" in flutter...                        
> pub upgrade failed (1)
> ```

Just change the version of font_awsome_flutter to  ^8.4.0

**Comment by brianegan** [comment]
Yep, sounds like you're using an old version of the package! Please update to the latest for Dart 2 support
