### ISSUE TITLE
font style issue

### ISSUE THREAD

**Issue by Falsammarraie** [brianegan/font_awesome_flutter#45]
https://github.com/brianegan/font_awesome_flutter/blob/8c5c152cea569c7deffb8acbf136bf8f2ac23cfb/tool/generate_font.dart#L37 should be changed to "style," because it's only pulling the first style (probably solid), which breaks the generator when trying to generate fonts with more than 2 styles

**Comment by BadTasTe-** [comment]
Is it working for you? I've changed styles.first with style in line 37 but it's still not working.

**Comment by Falsammarraie** [comment]
What issue are you getting? mine was that it was not using the light style

**Comment by BadTasTe-** [comment]
The only icons working are those with a single style, others are just rendered with a question mark in a box

**Comment by Falsammarraie** [comment]
the box probably means that the unicode for icon doesn't exist in the .ttf file you're using, the problem for me was that icons that were supposed to be different looked the same

**Comment by michaelspiss** [comment]
This issue is already fixed in #37, just waiting for merge.
