### ISSUE TITLE
Add `fromString` method

### ISSUE THREAD

**Issue by bartektartanus** [brianegan/font_awesome_flutter#46]
Add `fromString` method that will allow creating icons from strings. Eg:

`FontAwesome.fromString("addressCard")` should return `const IconDataRegular(0xf2bb)`

You can do this by generating another file with `Map<String, IconData>`

**Comment by brianegan** [comment]
Hey there -- This type of proposal has been [discussed in previous issues](https://github.com/brianegan/font_awesome_flutter/issues/10), and I'd like to avoid making this change for now. Different people have their strings stored in different ways.

If folks need to generate that kind of `fromString` method, I believe they should modify this code to do it in a way that makes sense for their individual projects.

**Comment by 24601** [comment]
@bartektartanus - we needed this feature and built http://github.com/VoltaireApp/icons_helper (https://pub.dev/packages/icons_helper) to implement it.

**Comment by ManojMM026** [comment]
This is needed!
