### ISSUE TITLE
font awesome versions >8.0.0 doesn't work on dart 2.4.0 - black box icon only

### ISSUE THREAD

**Issue by abdulmuaz97** [brianegan/font_awesome_flutter#50]
hey there..
I'm having problem with installing this package, currently I'm using **Dart 2.4.0** and when I tried installing **font-awesome** the version greater than **8.0.0**.. didn't work, it shows me a black box only on all icons.

then I tried install other version and I get error when I run `flutter packages get`
`Because MyApp depends on font_awesome_flutter >=4.7.1 <8.0.0 which requires SDK version <2.0.0, version solving failed.`

**any solutions?**

**Comment by GeekAbdelouahed** [comment]
@abdulmuaz97 have you tried uninstalling the app and installing it again ? . working for me

**Comment by MannyDiera** [comment]
@abdulmuaz97  just ran into this issue and as @GeekAbdelouahed suggested, uninstalling the app and reinstalling it fixed it for me.

**Comment by abdulmuaz97** [comment]
thank you I found a solution up there as friend there said.
