### ISSUE TITLE
FontAwesomeIcons not showing on Gutter bar in Android Studio

### ISSUE THREAD

**Issue by lodgmar** [brianegan/font_awesome_flutter#53]
What do I have to do to get FontAwesomeIcons showed on Gutter bar in Android Studio?

I have restarted IDE, recompiled app, but nothing happens. Icons display correctly in my app, but I really love viewing gutter icons in editor window.

**Comment by brianegan** [comment]
We've got a bug open with the Flutter IntelliJ folks! We can try to hack around it, but it requires a proper fix: https://github.com/flutter/flutter-intellij/issues/2334
