### ISSUE TITLE
Lots of icons are missing like.

### ISSUE THREAD

**Issue by jazzbpn** [brianegan/font_awesome_flutter#57]
Interest
Dancing
Conference
Publication
Reference
Tutorial
Yoga

**Comment by michaelspiss** [comment]
This package does not provide the icons themselves, but only a way to use them in your flutter projects. Please go to [fontawesome.com](https://fontawesome.com/) for a full list of supported icons or get a pro license over there to suggest/vote for new icons.

**Comment by jazzbpn** [comment]
How to get pro license in order to use this plugin in mobile application? Do we have to take license for all platform android and iOS and WEB or single license will work for all platform?

**Comment by michaelspiss** [comment]
I hope I could answer your question [over at your second issue](https://github.com/brianegan/font_awesome_flutter/issues/56#issuecomment-536468355).
