### ISSUE TITLE
Would be better if we can use the same image name while rendering in HTML.

### ISSUE THREAD

**Issue by jazzbpn** [brianegan/font_awesome_flutter#62]
Let say we need a **addressBook** Icon. In flutter we can render via  `Icon(
                                icon.iconData,
                                size: 100.0,
                              ),`

But when we want to use the same icon to render html page we have to use **address-book**. So, it would be better if you put key as real icons key like address-book by mapping the real name into that object property.

**Comment by michaelspiss** [comment]
Dart does not allow dashes (-) in variable names. That's why they are in lower camel case.

**Comment by jazzbpn** [comment]
You can create an object and put the real-name as a property. Thank you!!

**Comment by michaelspiss** [comment]
The dash (-) will be interpreted as a minus, so dart thinks you want to subtract `book` from `address` (neither is defined). That is why we cannot use dashes in the real names.
If this is it, please close the issue.
