### ISSUE TITLE
Showing Blank Boxes

### ISSUE THREAD

**Issue by AppleEducate** [brianegan/font_awesome_flutter#8]
## Description
When Running on Android it is showing blank boxes for the Font Awesome Icons, and Showing the correct ones for Flutter Icons. This was working when I installed it last week. I have also run `flutter clean` but still no luck.

![screenshot_20180507-101256](https://user-images.githubusercontent.com/31253215/39706496-a556ae94-51df-11e8-8479-659832a8de30.png)

## Flutter Doctor
```
Rodys-MBP:daily_nasa rodydavis$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.3.1, on Mac OS X 10.13.3 17D102, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 9.3)
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update, run:
        brew uninstall --ignore-dependencies libimobiledevice
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.23.0)
[✓] Connected devices (2 available)

! Doctor found issues in 1 category.
```

### Dependency
`font_awesome_flutter: 6.0.0`

### Use in Project
```
@override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        backgroundColor: Colors.white,
        title: new Text("Info"),
      ),
      body: new SingleChildScrollView(
        child: new ListBody(
          children: <Widget>[
            new Container(
              height: 10.0,
            ),
            new ListTile(
              leading: new Icon(FontAwesomeIcons.github),
              title: const Text('Github'),
              subtitle: new Text('@AppleEducate'),
              onTap: () {
                globals.Utility
                    .launchURL('https://www.github.com/appleeducate');
              },
            ),
            new Divider(
              height: 20.0,
            ),
            new ListTile(
              leading: new Icon(FontAwesomeIcons.twitter),
              title: const Text('Twitter'),
              subtitle: new Text('@RodyDavis'),
              onTap: () {
                globals.Utility.launchURL('https://www.twitter.com/rodydavis');
              },
            ),
            new Divider(
              height: 20.0,
            ),
            new ListTile(
              leading: new Icon(FontAwesomeIcons.facebook),
              title: const Text('Facebook'),
              subtitle: new Text('@RodyDavis'),
              onTap: () {
                globals.Utility.launchURL('https://www.facebook.com/rodydavis');
              },
            ),
            new Divider(
              height: 20.0,
            ),
            new ListTile(
              leading: new Icon(Icons.apps),
              title: const Text('Apps'),
              subtitle: new Text('by Rody Davis'),
              onTap: () {
                globals.Utility.launchURL('https://www.rodydavis.com/apps');
              },
            ),
            new Divider(
              height: 20.0,
            ),
            new ListTile(
              leading: new Icon(Icons.contact_mail),
              title: const Text('Contact'),
              subtitle: new Text('Submit Issues and Questions'),
              onTap: () {
                globals.Utility.launchURL('https://www.rodydavis.com/about');
              },
            ),
            new Divider(
              height: 20.0,
            ),
            new ListTile(
              leading: new Icon(FontAwesomeIcons.spaceShuttle),
              title: const Text('NASA'),
              subtitle: new Text('All Images provided by API'),
              onTap: () {
                globals.Utility.launchURL('https://api.nasa.gov/');
              },
            ),
            new Divider(
              height: 20.0,
            ),
            new ListTile(
              leading: new Icon(Icons.info),
              title: const Text('Version'),
              subtitle: new Text('$_projectVersion ($_projectCode)'),
              trailing: new Text('$_platformVersion'),
            ),
          ],
        ),
      ),
    );
  }
```

**Comment by brianegan** [comment]
Thanks for the report! I'm currently traveling, but will have look next week to see what's going on to if I need to make any upgrades to work with the latest beta.

**Comment by a-leblond** [comment]
I am facing the same issue for about 2 weeks and i was about to ask, thanks for the quick response !

**Comment by brianegan** [comment]
Hey hey -- could you both try the example app found within this repo to see if it works for ya? I just ran that app with the latest Flutter beta, checked the icons listed in the sample code, and didn't experience any issues. Therefore, we might need to dig a bit deeper, and it would be great to know if the example app is failing for you as well!

Thanks all :)

**Comment by a-leblond** [comment]
Hi ! 
I just tested the example app and it works fine on both platforms. I'm not sure why it's not working in my project only on Android devices.
I don't get any error in the logs, it is just showing blank boxes like @AppleEducate.

Here are my Flutter Doctor logs : 

> Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.3.2, on Mac OS X 10.13.4 17E199, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
[✓] Android Studio (version 3.1)
[✓] Connected devices (2 available)
No issues found!
Process finished with exit code 0

Of course i'm using the latest version of font_awesome_flutter. 

If you need more informations don't hesitate ! :)

**Comment by brianegan** [comment]
Hrm, odd -- is your code open source by any chance? Would be happy to clone it and see if I can reproduce the problem locally and try to find a fix.

**Comment by a-leblond** [comment]
Unfortunately the code of the app i'm working on is not open source but I can give you snippets of code or more informations like the dependencies : 

```
dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_database: 0.4.6
  cloud_firestore: 0.7.0
  firebase_auth: 0.5.9
  firebase_storage: 0.3.4
  google_sign_in: 3.0.1
  image_picker: 0.4.1
  shared_preferences: 0.4.1
  flutter_parallax: "^0.1.1"
  image: 1.1.31
  font_awesome_flutter: 6.0.0
  validator: ">=0.0.4 <0.1.0"
  flutter_launcher_icons: "^0.2.0"
```

Maybe it's a conflict with other dependencies ? @AppleEducate can share yours and see if we have some in common ?

**Comment by brianegan** [comment]
Thanks @AppleEducate! Hrm, this is an interesting one -- when I run your app on my emulator or real device, the Icons are showing up. We may need to file a bug against the Flutter repo itself since it seems to be working inconsistently.

Before we do that, as a test, I moved the location of the font files a bit to see if this might work for your projects. If you get a chance, please try to the following branch in your pub spec instead of version 6.0.0

```yaml
dependencies:
  font_awesome_flutter:
    git:
      url: git://github.com/brianegan/font_awesome_flutter.git
      ref: fonts-in-package
```

Screenshot of your app + version 6.0.0, working on my end :/

![screenshot_1526199474](https://user-images.githubusercontent.com/126604/40014309-12399fbe-5765-11e8-8903-0e706dd60d9d.png)

**Comment by AppleEducate** [comment]
Sure thing I will try that today!

**Comment by AppleEducate** [comment]
When I ran the project again today the images have returned and its working normally. Not sure what changed. Thanks for the help!

**Comment by brianegan** [comment]
Thanks @AppleEducate --  @a-leblond Are you still experiencing this problem?

**Comment by a-leblond** [comment]
I'll try my app and AppleEducate's app today, and see if it is fixed for me or not. I'll let you know !

**Comment by a-leblond** [comment]
So my app display the icons on an emulator with Android 6.0 but not on my Galaxy S8 (Android 8.0), and @AppleEducate's app works normally on my GS8. I tried to uninstall before install but it change nothing.
It is weird... Maybe it is some sort of cache or something like that ?

**Comment by a-leblond** [comment]
Ok i works ! :D 
I had to delete the app from my device, clean all the temporary files and caches from the device, make a flutter clean in my project, reboot the device and reinstall the app.
Don't know why it was doing this but now it works, thanks for the help ! :)

**Comment by volgin** [comment]
In case anyone runs into this issue, I had the same problem with v. 8.2.0. Restarting the app resolved it.

**Comment by Prashant09mca** [comment]
The current Dart SDK version is 2.6.0-dev.1.0.flutter-d6c6d12ebf.



Because web_tesing_demo depends on font_awesome_flutter from git which requires SDK version <2.0.0, version solving failed.
pub get failed (1)

**Comment by kininge** [comment]
I am working on Android 9.0 physical device and Icons are showing empty boxes for me. I will try to restart and try again.

**Comment by VictorPetch** [comment]
Same thing happened to me, but with custom icons. I'm not sure rebuilding the app is the answer, because I had no success in a couple of days and I had to reinstall the project every time I start working on it. But I ran flutter clean and restarted the app (not even reinstalled it). Not sure why, but it works.
