### ISSUE TITLE
Syringe icon is missing 

### ISSUE THREAD

**Issue by biscuitrainbow** [brianegan/font_awesome_flutter#9]
Another in medical category is missing too.

**Comment by brianegan** [comment]
Thanks, I'll take a look

**Comment by brianegan** [comment]
Looks like they've been added to a recent release! I'll try to find some time in the next week or two to add them.

**Comment by pplante** [comment]
I think this can be solved with #12.

**Comment by brianegan** [comment]
This is now fixed, will push a new version soon!

**Comment by brianegan** [comment]
Version 7.0.0 pushed with these icons.
